project:
  render:
    - discussion.qmd
    - introduction.qmd
    - propositions.qmd
bibliography: ../library.bib
biblio-style: authoryear
execute:
  cache: true
format:
  pdf:
    documentclass: article
    number-sections: true
    cite-method: biblatex
    keep-tex: true
    toc: false
    margin-left: 20mm
    margin-right: 20mm
    include-in-header:
      text: |
        \usepackage{lineno}\linenumbers
  docx:
    toc: false
    cite-method: biblatex
    number-sections: true
    highlight-style: github
