---
output-file: "propositions"
---

**Propositions**

1. The same statistical models used in other hybrid crops are amenable to hybrid potato
\newline (this thesis)
2. Starting a new hybrid breeding program without quantitative genetic theory is unlikely to succeed
\newline (this thesis)
3. Potato is just a vegetable masquerading as a field crop
4. It is professionally disqualifying to foster the adoption of generative AI in academia
5. Publically funded research is a better model than public-private consortiums
6. Higher education institutions are responsible for upholding international law
7. Dutch sandwich culture is excessively frugal and passionless

  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \
  \










Propositions belonging to the thesis, entitled 
 
A Statistical Evaluation of Hybrid Potato Breeding
 
James Adams
Wageningen, October 1^st^, 2026


:::{.content-hidden}

4. Hybrid breeding essentially hampers proper utilisation of innovation for the commons
2. Statistical genetics still forms a core domain for driving and evaluating genetic progress in new crops
\newline (this thesis)
* Most problems which the applied plant sciences attempt to address are political in nature rather than technical.
3. Hybrid breeding schemas are a benefit to crops with large trait surfaces
3. Geneticists would be better served by rigorous testing of molecular markers over pattern-hunting expeditions in spread sheets.
5. Attempting to incorporate high-dimensional biological information into predictive statistical models, _at best_, only leads to marginal benefits in crop breeding.
* Crop breeding, even in the age of artificial intelligence, will not change the substantially the formula of finding -> using -> regenerating

* If we truly care about the replication crisis in science, then insentive structures within universities, departments, and journals must be drastically changed. 

* The most ambitous breeding projects of the 20th century happened within the communist block rather than within privatised breeding companies.

* Breeding crops for climate change is like designing the perfect burger to ameliorate obesity.

* The problem is not that the Dutch enjoy sandwiches too liberally, but that the whole sandwich affair from preparation to ingurgitation is performed without so much as a modicum of passion.

* Geneticists are much too easily distracted by markers. Geneticist are much too easily fooled by markers. Sirens are to Sailers what markers are to Geneticists.

* More PhD's would finish on time if they received _a cut_ of the department distribution fund.

* More information content in a model does not necessarily make for better performance
4. Breeding _climate-ready_ crops is like designing _obesity-proof_ burgers
5. Putting more information into statistical models, _at best_, only leads to marginal benefits
:::


